image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: |
    yarn
    yarn build
    python -m pip install -r requirements.txt
    python manage.py migrate
    python manage.py createcachetable
    python manage.py buildfixtures
    echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'changeme')" | python manage.py shell
    echo "CSRF_TRUSTED_ORIGINS = ['https://*.gitpod.io']" >> apps/guide/settings/local.py
  command: |
    cd /workspace/guide
    python manage.py runserver 0.0.0.0:8080
github:
    prebuilds:
        pullRequestsFromForks: true
vscode:
  extensions:
    - ms-python.python
